### ISSUE TITLE
Customise information

### ISSUE THREAD

**Issue by kmaustral** [anpigon/obsidian-book-search-plugin#2]
Thanks for this wonderful plugin. It has great promise.

Would there be a way of customising the way the information you draw from API is presented? This would include information to go into the body as well as YAML. The QuickAdd IMDB movie script by Christian Hausman enables that. 

I look forward to seeing this develop.

**Comment by anpigon** [comment]
> Thanks for this wonderful plugin. It has great promise.
> 
> Would there be a way of customising the way the information you draw from API is presented? This would include information to go into the body as well as YAML. The QuickAdd IMDB movie script by Christian Hausman enables that. 
> 
> I look forward to seeing this develop. 

@kmaustral Thank you for the good idea. I'll try.

**Comment by ReaderGuy42** [comment]
Hi, not sure I'm understanding the original issue correctly, but maybe my request is similar:
Would it be possible to make the variable names in the front matter customizable? That way we could change things to our liking. E.g. I'd make "cover_url" into just "Cover" because I don't like "_".

Also, maybe it would be possible to make the created note titles customizable too?

Thanks for making this, it's great!

**Comment by eleanorkonik** [comment]
Thirding this, I would love to be able to move these from YAML down into dataview-friendly inline keypairs with some sort of templating setup, instead of setting up a templater script for it. This would let me align the things I bring it with this plugin with my Readwise templates. 

Also, thank you for this amazing plugin!

**Comment by anpigon** [comment]
Thanks for the idea.

**Comment by TinkerSquirrel** [comment]
Yes please. Being able to customise things and transform them to something dataview-compatible would be wonderful.

Great plugin so far though, makes book notes much easier to create!

**Comment by anpigon** [comment]
Thanks to your ideas, added the ability to use template files in version 5.2.0. Thank you.
